image: selenium/standalone-chrome:latest

before_script:
  - export GRADLE_USER_HOME="$CI_PROJECT_DIR/.gradle"

test:
  stage: test
  script:
    - gradle test
  artifacts:
    paths:
      - build/reports/tests/test
    expire_in: 1 week
