stages:
  - build
  - test

before_script:
  # Ensure Java is installed (you can customize the version based on your requirements)
  - echo "Setting up environment"
  - java -version
  - gradle -v

build:
  stage: build
  script:
    # Run the Gradle build (compiling and packaging the code)
    - echo "Building the project with Gradle"
    - gradle build --info
  artifacts:
    # Optionally save the build artifacts (e.g., the JAR files)
    paths:
      - build/libs
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    # Run the Gradle tests
    - echo "Running tests with Gradle"
    - gradle clean test --info
  artifacts:
    # Optionally save the test results as artifacts
    paths:
      - build/test-results/test
    expire_in: 1 week
  only:
    - master
