stages:
  - build
  - test

# Build stage
build:
  stage: build
  image: gradle:8.11.1-jdk21
  script:
    - gradle clean build

# Test stage using selenium/standalone-chrome image
test:
  stage: test
  image: selenium/standalone-chrome:latest
  services:
    - selenium/standalone-chrome:latest
  before_script:
    # Install Gradle into the selenium container (only if it's not already installed)
    - apt-get update && apt-get install -y wget unzip
    - wget https://services.gradle.org/distributions/gradle-8.11.1-bin.zip
    - unzip gradle-8.11.1-bin.zip
    - mv gradle-8.11.1 /opt/gradle
    - export PATH=$PATH:/opt/gradle/bin
    - gradle -v # Check Gradle version
  script:
    - gradle test # Run tests
  artifacts:
    paths:
      - build/reports/tests/test
    expire_in: 1 week
